# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main
      - dev
      - feature-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3

      - name: Проверка работы CI
        run: echo "Привет! CI запущен успешно ✅"
